PZPP Web/Models/PingViewModel.cs
using PZPP_Web.Data_Validations;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PZPP_Web.Models
{
    public class PingViewModel
    {
        public PingViewModel()
        {
            DropDown = new List<SelectListItem>();
            Selected = new List<string>();
        }

        [Required]
        [IP(ErrorMessage = "błędne ip")]
        [Display(Name = "IP")]
        public string IP { get; set; }

        
        [Display(Name = "Descriptions")]
        public string Description { get; set; }

        public IEnumerable<SelectListItem> DropDown { get; set; }
        public IEnumerable<string> Selected { get; set; }
    }
}

PZPP Web/Controllers/PingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using DataBase;
using PZPP_Web.Models;

namespace PZPP_Web.Controllers
{
    [Authorize]
    public class PingController : Controller
    {
        // GET: Ping
        public ActionResult Index()
        {
            var model = new PingViewModel();
            var d = new List<SelectListItem>();
            using (var db = new PingDataContext())
            {

                foreach (var item in db.Devices)
                {

                    d.Add(new SelectListItem() { Text = item.IP + " " + item.Description });

                }
                model.DropDown = d;
            }
            return View(model);
        }

        public ActionResult Responses()
        {
            List<ResponseModel> model = new List<ResponseModel>();
            using (var db = new PingDataContext())
            {
                foreach (var item in db.Responses)
                {
                    model.Add(new ResponseModel() {
                        Id =item.Id,
                        Device_Id= item.Device_Id,
                        Success= item.Success,
                        PingTime=item.PingTime,
                        Time=item.Time
                    });                    
                }
            }
            return View(model);
        }
        public ActionResult Devices()
        {
            List<DeviceModel> model = new List<DeviceModel>();
            using (var db = new PingDataContext())
            {
                foreach (var item in db.Devices)
                {
                    model.Add(new DeviceModel()
                    {
                        Id = item.Id,
                        IP = item.IP,
                        Description = item.Description

                    });
                }
            }
            return View(model);
        }
        [Authorize(Roles = "Moderator")]
        public ActionResult AddDevice(PingViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var db = new PingDataContext())
                {

                    db.Devices.Add(new Devices() { IP = model.IP, Description = model.Description });
                    db.SaveChanges();

                }
                return RedirectToAction("Index");

            }

            // If we got this far, something failed, redisplay form
            return View("Index", model);

        }
        [Authorize(Roles = "Admin")]
        public ActionResult PingDevice(PingViewModel model)
        {
            
            Ping pinger = new Ping();
            try
            {
                string data = model.Selected.First().ToString();
                string address = data.Remove(data.IndexOf(" "));
                // var id = IdControl[_SelectedDevice];//bierze id zaznaczonego urządzenia 
                PingReply reply = pinger.Send(address);//przypisanie jakie ip pingujemy 
                using (var db = new PingDataContext())
                {
                    if (reply.Status == IPStatus.Success)//jeśli ping się powiódł 
                    {

                        db.Responses.Add(new Responses() //sapisanie donych do bazy
                        {
                            Device_Id = db.Devices.Where(x => x.IP == address).Where(x => data.Contains(x.Description)).First().Id,
                            Success = true,
                            PingTime = reply.RoundtripTime,//czas pingu (ms)
                            Time = DateTime.Now//Data pingu
                        });
                    }
                    else//jak się nie udał
                    {

                        db.Responses.Add(new Responses()
                        {

                            Device_Id = db.Devices.Where(x => x.IP == address).Where(x => data.Contains(x.Description)).First().Id,
                            Success = false,
                            Time = DateTime.Now


                        });
                    }
                    db.SaveChanges(); //zapis danych do bazy (zostaje przesłane do bazy SQL)
                }
             
            }
            catch (PingException)
            {
                // Discard PingExceptions and return false;
            }           
                        
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult DeleteR(int id)
        {

            using (var db = new PingDataContext())
            {
                Responses Response = new Responses() { Id = id };
                db.Responses.Attach(Response);
                db.Responses.Remove(Response);
                db.SaveChanges(); //zapis danych do bazy (zostaje przesłane do bazy SQL)
            }
            return RedirectToAction("Responses");
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {

            using (var db = new PingDataContext())
            {
                Devices Device = new Devices() { Id = id };
                db.Devices.Attach(Device);
                db.Devices.Remove(Device);
                db.SaveChanges(); //zapis danych do bazy (zostaje przesłane do bazy SQL)
            }
            return RedirectToAction("Devices");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            DeviceModel model = new DeviceModel();
            using (var db = new PingDataContext())
            {
                model.Id = id;
                model.IP = db.Devices.Where(x => x.Id == id).First().IP;
                model.Description = db.Devices.Where(x => x.Id == id).First().Description;

            }
            return View("EditDevice",model);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult EditDevice(DeviceModel model)
        {
            using (var db = new PingDataContext())
            {
                db.Devices.Where(x => x.Id == model.Id).First().IP = model.IP;
                db.Devices.Where(x => x.Id == model.Id).First().Description = model.Description;
                db.SaveChanges();
            }
            return RedirectToAction("Devices");
        }
    }
}

PZPP Web/Views/Ping/Devices.cshtml
@model IEnumerable<PZPP_Web.Models.DeviceModel>

@{
    ViewBag.Title = "Devices";
}

<h2>Devices</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
            @if(User.IsInRole("Moderator"))
            { 
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |                    
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                </td>
            }
    </tr>
}

</table>

PZPP Web/Views/Ping/EditDevice.cshtml
@model PZPP_Web.Models.DeviceModel

@{
    ViewBag.Title = "EditDevice";
}

<h2>EditDevice</h2>

@using (Html.BeginForm("EditDevice", "Ping"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DeviceModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.IP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Devices")
</div>

PZPP Web/Views/Ping/Index.cshtml
@model PZPP_Web.Models.PingViewModel

@{
    ViewBag.Title = "Ping";
}

<h2>Ping</h2>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("Moderator"))
                {
                    using (Html.BeginForm("AddDevice", "Ping", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.IP, htmlAttributes: new { @class = "control-label col-md-2" })
                            </div>
                            <div class="form-group">
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.IP, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.IP, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            </div>
                            <div class="form-group">
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-10 col-lg-12">
                                    <input type="submit" value="Add" class="btn btn-default btn-block" />
                                </div>
                            </div>
                        </div>
                    }
                }
            }
        </div>
        <div class="col-md-8">
            @if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("Admin"))
                {
                    using (Html.BeginForm("PingDevice", "Ping", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.DropDown, htmlAttributes: new { @class = "control-label col-md-2" })
                            </div>
                            <div class="form-group">
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.Selected, Model.DropDown, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-10 col-lg-12">
                                    <input type="submit" value="Ping" class="btn btn-default btn-block" />
                                </div>
                            </div>
                        </div>
                    }
                }
            }
            
        </div>
    </div>
    
</div>

PZPP Web/Views/Ping/Responses.cshtml
@model IEnumerable<PZPP_Web.Models.ResponseModel>

@{
    ViewBag.Title = "Responses";
}

<h2>Responses</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Device_Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Success)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PingTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Device_Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Success)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PingTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>            
            @Html.ActionLink("Delete", "DeleteR", new { id=item.Id })
        </td>
    </tr>
}

</table>